# .github/release.yml

changelog:
  categories:
    - title: Nouveautés 🎉
      labels:
        - feat
    - title: Correctifs 🐛
      labels:
        - fix
    - title: Technique 🥷
      labels:
        - chore
    - title: Autres 🎁
      labels:
        - "*"
