#!/usr/bin/env bash

set -euo pipefail

export PRODUCT_NAME="api-communs-numeriques"
export REPO_NAME="api-communs-numeriques"
export GITHUB_ORGANIZATION="ccas-produits-numeriques"

# 1Password
export OP_VAULT_NAME="vault-passwords-common"
export OP_ACCOUNT="YKJS4EWTRJBINB7ARDPFJZUJUM"

# Vaultwarden
export VAULT_KV_MOUNT="sij-vault"

export BIN_DIR="$(dirname -- "$( readlink -f -- "$0"; )")"
export BIN_SHARED_DIR="$BIN_DIR/shared"
export ROOT_DIR="$(dirname "${BIN_DIR}")"
export SCRIPTS_DIR="$BIN_DIR/scripts"
export SCRIPTS_SHARED_DIR="$BIN_SHARED_DIR/scripts"

. "${BIN_DIR}/commands.sh"

################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################

readonly command=${1:-}

if [ -z "${CI:-}" ]; then
  _dispatch "dev:dependencies:check"
fi

case "$command" in
  ""|help|-h|--help) _help; exit 0 ;;
  *) shift; _dispatch "$command" "${@:-}" ;;
esac
