name: Update Documentation

on:
  pull_request:
    paths:
      - "sdk/src/docs/**/*.md"

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Transpile markdown
        run: pnpm --filter api-communs-numerique-sdk markdown:transpile

      - name: Run Prettier
        run: pnpm prettier:fix

      - name: typecheck
        run: pnpm typecheck

      - name: Run Lint with fix
        run: pnpm lint --fix

      - name: Commit changes if any
        run: |
          git config user.name "mna-devops[bot]"
          git config user.email "71841503+mna-devops@users.noreply.github.com"
          if git diff --quiet ./sdk/src/docs; then
            echo "No changes to commit"
            exit 0
          fi
          git add ./sdk/src/docs
          git commit -m "docs: update documentation" --no-verify
          git push
