name: Build
on:
  push:
    branches: [main]

jobs:
  tests:
    uses: "./.github/workflows/ci.yml"

  build:
    strategy:
      matrix:
        environment: [recette, production]
    uses: "./.github/workflows/_build.yml"
    with:
      environment: ${{ matrix.environment }}
      skip: false
    secrets:
      SLACK_WEBHOOK_NOTIF: ${{ secrets.SLACK_WEBHOOK_NOTIF }}
      OPENPGP_PRIVATE_SUBKEY: ${{ secrets.OPENPGP_PRIVATE_SUBKEY }}
      SHARED_BIN_TOKEN: ${{ secrets.SHARED_BIN_TOKEN }}
